### ISSUE TITLE
I cant start it

### ISSUE THREAD

**Issue by BrayantVideos1** [fquer/Rocket-League-Garage-Chatter#1]
### Hi, Can you make a .exe for this i would like to use it but i cant start it i get this error: 

```
line 1, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PyQt5' 
```

and i cant fix it. 

But [Rocket League Trade Price Checker Script] that requires the sames drivers i can run it.

**Comment by fquer** [comment]
Yeah executable is here : https://github.com/fquer/Rocket-League-Garage-Chatter/releases/tag/v1.0
For error you need to install PyQt5
Open Anaconda Promt and write pip install PyQt5

**Comment by BrayantVideos1** [comment]
iit worked, tysm.
